routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');



Route::resource('user', App\Http\Controllers\UserController::class);



Route::get('basket/reserved', [App\Http\Controllers\basketController::class, 'seeReservation'])->name('basket.reservation');

Route::get('basket/validated', [App\Http\Controllers\basketController::class, 'seeValidateBasket'])->name('basket.validated');

Route::get('basket/historic', [App\Http\Controllers\basketController::class, 'historic'])->name('basket.historic');

Route::resource('basket', App\Http\Controllers\basketController::class);

Route::get('basket/tryValidate/{basket}', [App\Http\Controllers\basketController::class, 'tryValidateBasket'])->name('basket.tryValidate');

Route::post('basket/validate/{basket}', [App\Http\Controllers\basketController::class, 'validateBasket'])->name('basket.validate');

Route::post('basket/accepted/{basket}', [App\Http\Controllers\basketController::class, 'acceptedBasket'])->name('basket.accepted');

Route::post('basket/finished/{basket}', [App\Http\Controllers\basketController::class, 'finishedBasket'])->name('basket.finished');

Route::get('basket/canceled/{basket}', [App\Http\Controllers\basketController::class, 'canceledBasket'])->name('basket.canceled');


Route::resource('product', App\Http\Controllers\productController::class);

Route::post('product/addProduct/{product}', [App\Http\Controllers\productController::class, 'addProductToBasket'])->name('product.addProduct');

Route::post('product/delProduct/{product}', [App\Http\Controllers\productController::class, 'delProductToBasket'])->name('product.delProduct');



Route::resource('category', App\Http\Controllers\categoryController::class);


require __DIR__.'/auth.php';

app/Models/product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'brand',
        'reference',
        'active',
        'stock',
        'previsionalStock',
        'image',
        'description',
        'id_category',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_category' => 'integer',
    ];

    public function baskets()
    {
        return $this->belongsToMany(Basket::class, 'basket_product', 'product_id', 'basket_id')->withPivot(['quantity', 'dateAddProduct']);
    }

    public function Category()
    {
        return $this->belongsTo(Category::class);

    }
}

app/Http/Controllers/productController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Basket;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Date;
use Spatie\SimpleExcel\SimpleExcelReader;
use Spatie\SimpleExcel\SimpleExcelWriter;
use App\Http\Requests\productStoreRequest;
use App\Http\Requests\productUpdateRequest;

class productController extends Controller
{

    public function index(Request $request)
    {
        $products = Product::all();
        $categories = Category::all();

        if(auth()->check()){
            $user = Auth::user();
            $baskets = $user->basket;

            foreach ($baskets as $value){
                if($value->state == 'draft'){
                    $basket = $value;
                }
            }

            $productsBasket = $basket->products;
            $nbProductBasket = 0;

            foreach($productsBasket as $productBasket){
                $nbProductBasket += $productBasket->pivot->quantity;
            };

            return view('product.index', compact(['products', 'basket', 'categories', 'nbProductBasket']));
        } else {

            return view('product.index', compact(['products', 'categories']));
        }
    }


    public function create()
    {

    }

    //enregistrement produit via formulaire
    public function store()
    {

    }


    public function show(Request $request, product $product)
    {

        return view('product.show', compact('product'));
    }


    public function edit(Request $request, product $product)
    {

    }


    public function update(Request $request, product $product)
    {

    }


    public function destroy(Request $request, product $product)
    {

    }


    public function addProductToBasket(product $product)
    {
        $user = Auth::user();
        $baskets = $user->basket;

        foreach ($baskets as $value){
            if($value->state == 'draft'){
                $basket = $value;
            }
        }

        $quantity = request('quantity');

        if($product->previsionalStock >= $quantity && $quantity >= 1){
            $product->previsionalStock -= $quantity;
            $product->save();

            $itemBasket = $basket->products;

            foreach($itemBasket as $item){
                if($product->id == $item->pivot->product_id){
                    $item->pivot->quantity += $quantity;
                    $item->pivot->save();

                    return redirect()->route('product.index');
                };
            };

            $basket->products()->attach($product);
            $basket->products()->updateExistingPivot($product, ['quantity'=>$quantity]);
            $basket->products()->updateExistingPivot($product, ['dateAddProduct'=>Date::now()]);

            return redirect()->route('product.index');

        } else {
            return redirect()->route('product.index')->with('message', 'Stock insuffisant !');
        }
    }


    public function delProductToBasket(product $product)
    {

        $user = Auth::user();
        $baskets = $user->basket;

        foreach ($baskets as $value){
            if($value->state == 'draft'){
                $basket = $value;
            }
        }
        $quantity = request('quantity');

        $product->previsionalStock += $quantity;
        $product->save();

        $itemBasket = $basket->products;
        foreach($itemBasket as $item){
            if($product->id == $item->pivot->product_id){
                if($quantity == $item->pivot->quantity){
                    $basket->products()->detach($product);

                    return redirect()->route('basket.show', ['basket'=>$basket]);
                } else {
                    $item->pivot->quantity -= $quantity;
                    $item->pivot->save();

                    return redirect()->route('basket.show', ['basket'=>$basket]);
                };
            };
        }
    }

}

resources/views/product/create.blade.php
@vite(['resources/scss/app.scss', 'resources/js/app.js'])

@include('components.perso.header')
<br>
<div class="pageAddProduct">
    <div class="row">
        <h2>Importer vos données via formulaire</h2>
        <form class="col-8 d-flex flex-column justify-content-center" method="POST"  enctype="multipart/form-data" action="{{ route('admin.product.store') }}">
            @csrf
                <label for="name" class="form-label">Nom du produit</label>
                <input type="text" class="form-control" name="name">

                <label for="brand" class="form-label">Marque du produit</label>
                <input type="text" class="form-control" name="brand">

                <label for="reference" class="form-label">Reference</label>
                <input type="text" class="form-control" name="reference" maxlength="8">

                <label for="stock" class="form-label">Stock</label>
                <input type="number" class="form-control" name="stock">

                <label for="filepath" class="form-label">Image du produit</label>
                <input type="file" class="form-control" name="filepath">

                <label for="description" class="form-label">Description du produit</label>
                <textarea class="form-control" rows="5" name="description"></textarea>

                <label for="id_category" class="form-label">Catégorie</label>
                <select class="form-select" aria-label="Default select example" name="id_category">
                    <option selected>Selectionner une catégorie</option>
                    @foreach($categories as $category)
                        <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </select>
                <br>
                <div class="">
                    <button type="submit" class="btn btn-dark">Ajouter</button>
                </div>

        </form>
    </div>
    <div class="row">
        <h2>Importer vos données via csv</h2>
        <form class="col-8 d-flex flex-column justify-content-center" method="POST"  enctype="multipart/form-data" action="{{ route('admin.product.storeViaCsv') }}">
            @csrf
                <label for="file" class="form-label">Fichier Csv à importer</label>
                <input id="file" type="file" class="form-control" name="file" required>

                <br>
                <div class="">
                    <button type="submit" class="btn btn-dark">Ajouter</button>
                </div>

        </form>
    </div>
</div>
<br>
@include('components.perso.footer')

resources/views/product/edit.blade.php
@vite(['resources/scss/app.scss', 'resources/js/app.js'])

@include('components.perso.header')


<div class="row">
    <div class="col-2"></div>
    <form class="col-8 d-flex flex-column justify-content-center" method="POST" action="{{ route('admin.product.update', ['product'=>$product]) }}">
        @csrf
        @method('PUT')
            <label for="name" class="form-label">Nom du produit</label>
            <input type="text" class="form-control" name="name" value="{{ $product->name }}">

            <label for="brand" class="form-label">Marque du produit</label>
            <input type="text" class="form-control" name="brand" value="{{ $product->brand }}">

            <label for="reference" class="form-label">Reference</label>
            <input type="text" class="form-control" name="reference" maxlength="8" value="{{ $product->reference }}">

            <label for="stock" class="form-label">Stock</label>
            <input type="number" class="form-control" name="stock" value="{{ $product->stock }}">

            <label for="filepath" class="form-label">Image du produit</label>
            <input type="file" class="form-control" name="filepath" value="{{ $product->image }}>

            <label for="description" class="form-label">Description du produit</label>
            <textarea class="form-control" rows="5" name="description">{{ $product->description }}</textarea>

            <label for="id_category" class="form-label">Catégorie</label>
            <select class="form-select" aria-label="Default select example" name="id_category">
                <option>Selectionner une catégorie</option>
                @foreach($categories as $category)
                    @if ($product->id_category === $category->id)
                        <option value="{{$category->id}}" selected>{{$category->name}}</option>
                    @endif
                    <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
            </select>

            <br>
            <div class="">
                <button type="submit" class="btn btn-dark">Modifier</button>
            </div>

    </form>
</div>

resources/views/product/index.blade.php
@vite(['resources/scss/app.scss', 'resources/js/app.js'])

@include('components.perso.header')
<div class="bodyProduct">
    <div class="categories">
        <h2 class="titleListCategory"><o>C</o>atégories</h2>
        <div class="category">
            <a href="{{ route('product.index') }}">¤ Tous les Produits</a>
            @foreach ($categories as $category)
                <a href="{{ route('category.show', ['category'=>$category]) }}">¤ {{ $category->name }}</a>
            @endforeach
        </div>
    </div>
    <div class="products">
        <div class="titleProduct">
            <h2><o>P</o>roduits</h2>
        </div>
        <div class="headTable">
            <table cellpadding="0" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Marque</th>
                        <th>Catégorie</th>
                        <th>Qté</th>
                        @if (auth()->check())
                            @if (Auth::user()->is_admin === 1)
                                <th>Modifier</th>
                            @else
                                <th>Panier</th>
                            @endif
                        @else
                            <th>Panier</th>
                        @endif
                    </tr>
                </thead>
            </table>
        </div>
        <div class="bodyTable">
            <table cellpadding="0" cellspacing="0">
                <tbody>
                    @foreach ( $products as $product)
                        <tr>
                            <td>{{ $product->name }}</td>
                            <td>{{ $product->brand }}</td>
                            <td>
                                @foreach ($categories as $category)
                                    @if ($product->id_category === $category->id)
                                        {{$category->name}}
                                    @endif
                                @endforeach
                            </td>
                            <td>{{$product->previsionalStock}}</td>
                            <td>
                                @if (auth()->check())
                                    @if (Auth::user()->is_admin === 1)
                                        <div class="modifProduct">
                                            <a href="{{ route('admin.product.edit', ['product'=>$product]) }}"><button>🖉</button></a>
                                            <form action="{{ route('product.destroy', ['product'=>$product]) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit">🗑</button>
                                            </form>
                                        </div>
                                    @else
                                        <form action="{{ route('product.addProduct', ['product'=>$product]) }}" method="POST">
                                            @csrf
                                            <input type="number" name="quantity" max="{{ $product->previsionalStock }}" min="1">
                                            <button type="submit" class="btn btn-primary"><img src="./images/panier.png" alt="image panier"></button>
                                        </form>
                                    @endif
                                @else
                                    <form action="{{ route('product.addProduct', ['product'=>$product]) }}" method="POST">
                                        @csrf
                                        <input type="number" name="quantity" max="{{ $product->previsionalStock }}" min="1">
                                        <button type="submit" class="btn btn-primary"><img src="./images/panier.png" alt="image panier"></button>
                                    </form>
                                @endif
                            </td>
                        </tr>
                        {{-- <a href="{{ route('product.show', ['product'=>$product]) }}"><button class="btn btn-danger">Voir detail produit</button></a> --}}
                        {{-- <div class="updateProduct">
                            <a href="{{ route('product.edit', ['product'=>$product]) }}"><button class="btn btn-primary">Modifier produit</button></a>
                        </div> --}}
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@include('components.perso.footer')

resources/views/product/show.blade.php
@vite(['resources/scss/app.scss', 'resources/js/app.js'])

@include('components.perso.header')

<h2>Détail du produit</h2>
<br>
{{$product}}

@include('components.perso.footer')